### PR TITLE
Use Hann window function for unfolded batch synthesis

### PR DESCRIPTION
**Pull request by begeekmyfriend**
Hann windowing funtion performs better for unfolding because of assert(fade_in + fade_out == np.ones(2 * overlap)) which would keep the fidelity of the waveform. Moreover It solves https://github.com/fatchord/WaveRNN/issues/78

Signed-off-by: begeekmyfriend <begeekmyfriend@gmail.com>

### CODE REVIEW

**Comment by fatchord** [comment]
@begeekmyfriend I disagree, a hann window is not a suitable for mixing audio samples in this context. An equal powers crossfade is very basic but it's more in line with how humans perceive loudness.

**Comment by begeekmyfriend** [comment]
I mean it would solve the discontinuity in waveform as #78 mentioned. What's more, there is no exceptional noises in synthesis results.

**Comment by fatchord** [comment]
It wouldn't necessarily solve the discontinuation as the waveforms cannot guaranteed to be the same and/or in the same phase. Hann is perfectly suitable for stft and other signal processing functions but the context here is that we are dealing with what is essentially an audio effect (the crossfade). 

The unit for loudness, the decibel, is on a logarithmic scale - in order to mimic a perceived linear increase in loudness you need some sort of exponential-like curve, hence why I am using the equal powers crossfade. The hann window is way too shallow at the start of the curve so it isn't suitable in this context - it would basically create a tremelo effect on the audio..

That isn't to say that the crossfade approach that is currently in the repo can't be improved. I'll admit that what I initially implemented is super basic.

**Comment by begeekmyfriend** [comment]
I respect your choice. However my colleage who is professional in signal processing says a perfect crossfade seqence shall meet such equation as follows. The `hann` windowing sequence meets such demand.
```python
assert(fade_in + fade_out == np.ones(2 * overlap))
```

**Comment by fatchord** [comment]
Well it looks like neither of us are going to agree on this so we may as wrap it up here.

**Pull request closed without merging**
